language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - '3.7-dev'
install:
  - make deps-pip deps-pip-test
script:
  - make assets-clean assets test OCRD_BASEURL="https://github.com/OCR-D/ocrd-assets/raw/master/data/"
